apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: issuer-prod
    kubernetes.io/ingress.class: traefik
  generation: 1
  name: py-toys
  namespace: py-toys
  labels:
    services: py-toys
spec:
  rules:
  - host: toys.pandas.run
    http:
      paths:
      - backend:
          service:
            name: py-toys
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - toys.pandas.run
    secretName: pytoys-tls
status:
  loadBalancer:
    ingress:
    - ip: 144.126.144.76
    - ip: 2605:a141:2103:3856::1
    - ip: 2605:a141:2103:3857::1
    - ip: 2605:a141:2109:8615::1
    - ip: 66.94.127.190
    - ip: 85.239.233.1
