apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-prod
  namespace: py-toys
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ryshan@pandas.run
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik