DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `posts`;
DROP TABLE IF EXISTS `speech`;

CREATE TABLE user (
  "user_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "user_name" VARCHAR(30) UNIQUE NOT NULL,
  "name" VARCHAR(80) NOT NULL,
  "password" VARCHAR(30) NOT NULL
);

CREATE TABLE posts (
    "post_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER NOT NULL,
    "created" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "title" VARCHAR(255) NOT NULL,
    "body" TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE speech (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "filepath" VARCHAR(255) NOT NULL,
    "desc" VARCHAR(255) DEFAULT '',
    "text" TEXT DEFAULT ''
);